name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: project-envuelto
      REGION: southamerica-east1
      # No need for FIREBASE_TOKEN since we'll use service account credentials

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Google Application Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Delete build folder
        run: rm -rf build

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:project-envuelto --project project-envuelto --non-interactive
